config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pets do
    resources :bookings, only: [:create, :new, :index]
  end
  resources :bookings, only: :destroy
  resources :pets, only: [:index, :show] do
    resources :reviews, only: :create
  end

  # Bookings of current User
  # Pets of current user
  get "dashboard/:id", to: "pages#dashboard", as: :dashboard
  get "map/", to: "pages#map", as: :map
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :pet_id, uniqueness: { scope: %i[user_id start_date] }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, presence: true
  validates :address, presence: true
  validates :species, presence: true, inclusion: { in: %w[dog cat piglet rabbit squirrel fish monkey],
    allow_nil: false }
  validates :city, presence: true
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: %i[name species category address city],
                  using: {
                    tsearch: { prefix: true }
                  }

  def check_species(input)
    case input
    when "dog"
      "dog.png"
    when "cat"
      "cat.png"
    when "piglet"
      "pig.png"
    when "monkey"
      "monkey.png"
    else
      "rabbit.png"
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pet
  validates :content, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews
  has_many :pets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name city])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  before_action :set_pet, only: %i[new create]

  def index
    @bookings = current_user.bookings
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.pet = Pet.find(params[:pet_id])
    @booking.save
    redirect_to dashboard_path(current_user)
  end

  private

  def booking_params
    params[:booking].permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pets = Pet.all.sample(3)
    @booking = Booking.all
  end

  def dashboard
    current_user_pets
    current_user_bookings
  end

  def map
    @pets = Pet.all
    # only Pets with coordinates
    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { pet: }),
        image_url: helpers.asset_url("green-paw.png")
      }
    end
  end

  private

  def current_user_pets
    @pets = Pet.where(user_id: current_user).all
  end

  def current_user_bookings
    @bookings = Booking.where(user_id: current_user).all
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_pet, only: %i[show]

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user # @pet.user_id = current_user.id
    @pet.save
    redirect_to pets_path
  end

  def index
    @pets = Pet.global_search(params[:query]) if params[:query].present?
    @specific_pet = params[:species]
    @specific_city = params[:city]
    @less_than_price = params[:price].to_i

    # if (@specific_pet == "" || @specific_pet.nil?) && (@specific_city == "" || @specific_city.nil?) && (@less_than_price == "" || @less_than_price.nil?)
    @pets = Pet.all
    # else
    #   raise
    #   @pets = Pet.where(species: @specific_pet).where(city: @specific_city).where("price < ?", @less_than_price)
    # end
  end

  def show
    @pet = Pet.find(params[:id])
    @review = Review.new
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :description, :city, :species, :age, :category, :photo, :address, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @pet = Pet.find(params[:pet_id])
    @review = Review.new(review_params)
    @review.pet = @pet
    respond_to do |format|
      if @review.save
        format.html { redirect_to pet_path(@pet) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render "pets/show", status: :unprocessable_entity }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="form-control" style="background-color:white;border: none">
    <h2>Book a date with <br><%= @pet.name %> ?</h2>
    <%= form_with model:  [@pet, @booking], authenticity_token: true do |f| %>
    <%= f.text_field :start_date, placeholder: 'Start Date', label:false,
      data: {
        controller: "flatpickr",
        flatpickr_date_format: "d-m-Y",
        flatpickr_min_date: Time.zone.now #disables past dates
      } %>
      <%= f.text_field :end_date, placeholder: 'End Date', label:false,
      data: {
        controller: "flatpickr",
        flatpickr_date_format: "d-m-Y",
        flatpickr_min_date: Time.zone.now #disables past dates
      } %>
      <div class="container d-flex justify-content-end">
        <%= f.submit class: "btn-green" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mb-4 mt-5 p-0" style="background-color: white; color: black; width: 1000px; height: 500px;z-index: 100;">
  <div class="d-flex justify-content-between p-0 m-0" style="background-color: white;">
    <% if @pet.photo.key%>
      <%= cl_image_tag @pet.photo.key, :height=>500, :width=>500, :fill=>"fill" %>
    <% else %>
      <div class="card-product-show">
        <div class="card-image-show">
          <div class="card-product img">
            <% if @pet.species == "dog" %>
              <%= image_tag ("https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80")%>
            <% elsif @pet.species == "monkey" %>
              <%= image_tag("https://images.unsplash.com/photo-1516636052745-e142aecffd0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1935&q=80")%>
            <% elsif @pet.species == "cat" %>
              <%= image_tag("https://images.unsplash.com/photo-1543852786-1cf6624b9987?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
            <% elsif @pet.species == "piglet" %>
              <%= image_tag("https://images.unsplash.com/photo-1617167152074-821b4f8af3d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
            <% elsif @pet.species == "rabbit" %>
              <%= image_tag("https://images.unsplash.com/photo-1591382386627-349b692688ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="mt-5" style="width: 600px;">
      <div class="form-actions" >
        <%= render 'bookings/form', pet: @pet, booking: @booking %>
      </div>
    </div>
  </div>

  <div class="" style="
  z-index: -2;
  top: -104px;
  position: relative;
  left: 853px;
  display: flex;
  justify-content: flex-start;
  align-items: self-end;">
    <div class="img-booking"  style="border: none;">
      <%= image_tag "huella.png", height: 300, class: "animal", style: "border: none;" %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="p-5 m-0" style="color: black; background-color:#f3eded; width:100%;">
  <div class="cards-dashboard">
    <br>
    <h4 >Welcome back <%= current_user.first_name.capitalize %> !</h4>
    <hr>
    <h5 class="p-0">My Bookings: </h5>
      <% if @bookings.length >0 %>
        <%= render 'shared/bookmark' %>
      <% else %>
        <h6>You don't have any bookings.</h6>
    <% end %>
    <hr>

    <h5>My Pets:
      <%= link_to new_pet_path do%>
        <button class="btn-sign-up float-end"><i class="fa-solid fa-circle-plus "></i> Add pet</button>
      <% end %>
    </h5>

    <% if @pets.length >0 %>
      <%= render 'shared/my_pet_card' %>
    <% else %>
      <h6>You have not added any pets.</h6>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class=" container d-flex justify-content-between align-items-center" style="height:80vh" >
  <div class="p-3 m-5" style="border-width: thick; height:330px;   border-style: solid;  border-width: 10px;
  border-color:white;">
    <div class="container" style="height:230px;">
      <h1>Welcome to <strong>Sweet paw! </strong> </h1>
      <p>We have all kind of pets here. Innocent? Mischievous? Grumpy? You name it. We have them.</p>

      <h1 class="text-shadow" style="font-size:20px">
      We are ready to share Pet Love!</h1>
      <br>

      <div class="d-flex">
        <a class="btn-sign-up me-3" href="/users/sign_up">Sign Up</a>
        <div>
            <%= form_with url: pets_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query,
              params[:query],
              class: "form-control btn-search",
              placeholder: "Find your pet" %>
            <%end %>
          </div>
        </div>
      </div>
    </div>

    <div class="d-flex justify-content-end flex-column align-items-end mb-3">
      <div style = "background-image: url(https://images.unsplash.com/photo-1608096281339-5bcae1ec2f12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80); width: 300px; height: 200px; border-width: thick;   border-style: solid;  border-width: 10px;
    border-color: rgb(255, 255, 255); background-size: cover; margin-bottom: 10px"></div>
      <div style = "background-image: url(https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80); width: 300px; height: 300px; border-width: thick;   border-style: solid;  border-width: 10px;
    border-color: rgb(255, 255, 255); background-size: cover;"></div>
  </div>
  <div class="mb-3 ms-3"style = "background-image: url(https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80); width: 350px; height: 450px; border-width: thick;   border-style: solid;  border-width: 10px;
  border-color: rgb(255, 255, 255); background-size: cover;"></div>
  </div>
</div>

app/views/pages/map.html.erb
<div class="container">
  <h3 class="text-center" style="color:black;" >Find a pet from the map!</h3>
    <div data-controller="map"
            id="map"
            class="map-sweet m-3"
            data-map-target="map"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            data-map-markers-value="<%=  @markers.to_json %>"
            style="width: 100%; height: 80vh; margin: 20px;">
    </div>
  <%= link_to pets_path do%>
    <button button class="btn-login position-fixed" style=" Z-index: 2; bottom: 100px; right:700px;"><i class="fa-solid fa-list"></i> List</button>
  <% end %>
</div>

app/views/pets/index.html.erb
<%= link_to map_path do%>
  <button class="btn-login position-fixed" style=" Z-index: 2; bottom: 100px; right:700px;"><i class="fa-regular fa-map"></i> Map</button>
<% end %>

<div data-controller="filter-pets">
  <div class=" container d-flex flex-row justify-content-end align-items-center mt-3" style="margin-left: 100px;">
    <div class="flex-grow-1">
      <%# <%= render "shared/search"%>
      <div>
        <button class="filter-button selected" id="all" data-action="click->filter-pets#clearFilter" data-filter-pets-target="allPets">All</button>
        <button class="filter-button" id="dog" data-action="click->filter-pets#filter" data-filter-pets-target="button">Dog</button>
        <button class="filter-button" id="cat" data-action="click->filter-pets#filter" data-filter-pets-target="button">Cat</button>
        <button class="filter-button" id="monkey" data-action="click->filter-pets#filter" data-filter-pets-target="button">Monkey</button>
        <button class="filter-button" id="pig" data-action="click->filter-pets#filter" data-filter-pets-target="button">Pig</button>
        <button class="filter-button" id="rabbit" data-action="click->filter-pets#filter" data-filter-pets-target="button">Rabbit</button>
      </div>
    </div>
    <div>
      <%= link_to new_pet_path do %>
        <button class="btn-sign-up"><i class="fa-solid fa-circle-plus "></i> Add pet</button>
      <% end %>
    </div>
  </div>
  <%= render "shared/cards" %>
</div>

app/views/pets/new.html.erb
<div class="container mb-4 mt-0 p-5" style="background-color: white; color: black; width: 800px; ">
  <%= simple_form_for(@pet) do |f| %>
    <h2 class= "text-center">Details of the Pet   <i class="fa-solid fa-paw" style="font-size: 30px; color: #225820; margin-right:10px"></i>
    </h2>
    <hr>
    <%= f.input :name %>
    <%= f.input :age %>
    <% f.label :species %>
    <%= f.input :species, as: :select, collection: [['Dog' , 'dog'], ['Cat', 'cat'], ['Piglet', 'piglet'],['Squirrel', 'squirrel'], [ 'Rabbit', 'rabbit'], ['Monkey', 'monkey'], ['Fish','fish']], prompt: 'Select your pet' %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :photo, as: :file %>
    <div class="form-actions-add-pet">
      <%= f.button :submit, "Add Pet", class:"btn-login" %>
    </div>
  <% end %>
</div>

app/views/pets/show.html.erb
<div class="d-flex justify-content-between">
  <div><%= link_to "Back to all Pets", pets_path, class: "btn-return m-5" %></div>
  <div><%= link_to "Book this Pet", new_pet_booking_path(@pet), class: "btn-book-pet m-5" %></div>
</div>

<div class="container-show">
  <div class="flex-wrap">
    <div class="img-fluid show-image animate__animated animate__rollIn animate__delay-.5s">
      <% if @pet.photo.key%>
        <%= cl_image_tag @pet.photo.key, :height=>500, :width=>500, :fill=>"fill" %>
      <% else %>
        <div class="card-product-show">
          <div class="card-image-show">
            <div class="card-product img">
              <% if @pet.species == "dog" %>
                <%= image_tag ("https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80")%>
              <% elsif @pet.species == "monkey" %>
                <%= image_tag("https://images.unsplash.com/photo-1516636052745-e142aecffd0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1935&q=80")%>
              <% elsif @pet.species == "cat" %>
                <%= image_tag("https://images.unsplash.com/photo-1543852786-1cf6624b9987?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
              <% elsif @pet.species == "piglet" %>
                <%= image_tag("https://images.unsplash.com/photo-1617167152074-821b4f8af3d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
              <% elsif @pet.species == "rabbit" %>
                <%= image_tag("https://images.unsplash.com/photo-1591382386627-349b692688ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="show-image">
      <h3 class="animate__animated animate__jackInTheBox animate__delay-.8s ">Allow me to introduce you to <%= @pet.name %> </h3>
      <p><%= @pet.category.capitalize %> <%= @pet.species %> </p>
      <p><%= @pet.name %> is <%= @pet.age %> years old.</p>
      <p><i class="fa-solid fa-location-dot">  </i> <%= @pet.address %></p>
      <br>
      <p style="font-weight: 400;"><strong>A little information about <%= @pet.name %> </strong> </p>
      <p><%= @pet.description %>🌈</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="show-info-pet animate__animated animate__jackInTheBox animate__delay-.8s">
    <div class="container" data-controller="insert-in-list">
      <%# < <h2><%= pluralize @pet.reviews.size, "review"</h2> %>
      <h2> Leave a review here</h2>
      <div data-insert-in-list-target="items">
        <% if @pet.reviews.blank? %>
          Be the first to leave a review for <%= @pet.name %>
        <% else %>
          <% @pet.reviews.each do |review| %>
            <%= render "reviews/review", review: review %>
          <% end %>
        <% end %>
      </div>
      <%= render 'reviews/form', pet: @pet, review: @review %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([pet, review], data: {insert_in_list_target: "form", action: "submit->insert-in-list#send"}) do |f|%>
  <%= f.input :content, as: :text %>
  <%= f.submit class: "btn-green"%>
<% end %>

app/views/reviews/_review.html.erb
 <p><i class="fa-solid fa-paw"></i> <%= review.content %></p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1573435567032-ff5982925350?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80);">
  <div class="container">
    <h1>Welcome to <strong>Sweet paw! </strong> </h1>
      <p>We have all kind of pets here. Innocent? Mischievous? Grumpy? You name it. We have them.</p>
      <a class="btn-sign-up" href="/users/sign_up">Sign Up</a>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="cards container">
  <% @pets.each do |pet| %>
    <div class="card-product shadow" data-filter-pets-target="pet">
      <div class="card-image">
        <%= link_to  pet_path(pet) do%>
          <% if pet.photo.key%>
            <%= cl_image_tag pet.photo.key, crop: "fill" %>
          <% else %>
            <% if pet.species == "dog" %>
              <%= image_tag("https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80")%>

            <% elsif pet.species == "monkey" %>
              <%= image_tag("https://images.unsplash.com/photo-1516636052745-e142aecffd0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1935&q=80")%>

            <% elsif pet.species == "cat" %>
              <%= image_tag("https://images.unsplash.com/photo-1543852786-1cf6624b9987?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>

            <% elsif pet.species == "piglet" %>
              <%= image_tag("https://images.unsplash.com/photo-1617167152074-821b4f8af3d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>

            <% elsif pet.species == "rabbit" %>
              <%= image_tag("https://images.unsplash.com/photo-1591382386627-349b692688ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")%>

            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="card-product-infos">
        <%= link_to  pet_path(pet) do%>
          <p class="info-name"><%= pet.name %></p>
        <% end %>
        <p> <%= pet.category.capitalize %> <%= pet.species.capitalize %></p>
        <div class="d-flex justify-content-between align-items-center" >
          <p style="font-size: 15px; "> <i class="fa-solid fa-euro-sign"></i> <%= pet.price %></p>
          <p  style="font-size: 13px; color: grey"> <%= link_to  new_pet_booking_path(pet) do%>
            <i class="fa-solid fa-heart ">  Book me</i>
          <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/dvnishshanka/sweet-paw" target="blank"><i class="fab fa-github"></i></a>
    Coded by the Book-Buddies
  </div>
  <div class="footer-copyright">
    We are ready to share pet <i class="fa-solid fa-heart" style="font-size: 15px; color: red;"></i>
  </div>
</div>

app/views/shared/_info_window.html.erb
<div style='float:left'>
  <%= image_tag pet.check_species(pet.species), height: 60, width: 60 %>
  <p><strong><i class="fa-solid fa-paw"></i> <%= pet.name %></strong></p>
  <p><%= pet.address %></p>
  <%= link_to "More info", pet_path(pet), class: "btn-map" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm  navbar-sweet-paw mt-0 sticky-top">
  <div class="container-fluid ">
    <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex flex-row align-items-center justify-content-center">
      <i class="fa-solid fa-paw" style="font-size: 30px; color: #225820; margin-right:10px"></i>
      <p style ="font-family: 'Pacifico', cursive; font-size: 30px; padding: 0 0; margin: 0 0;">SweetPaW</p>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link " %>
          </li>
          <li class="nav-item">
            <%= link_to  "All Pets", pets_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to  "Add Pet", new_pet_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" %>
          </li>

           <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn-login pl-50" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>